### ISSUE TITLE
catch UserWarning

### ISSUE THREAD

**Issue by bgadberr** [bgadberr/music_recommender#2]
UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@bgadberr  looks good can i do this

**Comment by bgadberr** [comment]
@RAJAGOPALAN-GANGADHARAN Yes, please!
